### ISSUE TITLE
import centergroup error

### ISSUE THREAD

**Issue by FereshtehFeiz** [dvl-tum/center-group#5]
Hello, 
for Training the centregroup with this command: 
 python tools/train.py --cfg configs/coco/centergroup/coco/higherhrnet_w32_coco_512x512.py --num_gpus 2 --out output --run_str my_training --cfg-options data.samples_per_gpu=1
 I got the below error: 
 File "tools/train.py", line 21, in <module>
    import centergroup
ModuleNotFoundError: No module named 'centergroup'

Could you please help me? 
Thank you

**Comment by calmiLovesAI** [comment]
Same Error. I tried to comment out this line of code, then there comes out another error:
```
TRAINING FROM SCRATCH
Traceback (most recent call last):
  File "tools/train.py", line 126, in <module>
    main()
  File "tools/train.py", line 108, in main
    model = build_posenet(cfg['model'])
  File "/home/featurize/mmpose/mmpose/models/builder.py", line 39, in build_posenet
    return POSENETS.build(cfg)
  File "/environment/miniconda3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/environment/miniconda3/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/environment/miniconda3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'CenterGroup is not in the models registry'
```

**Comment by calmiLovesAI** [comment]
I found a solution, you can add this before `import centergroup`
```
import sys
sys.path.append('$CENTERGROUP_ROOT')
```

**Comment by FereshtehFeiz** [comment]
I added, but I have the same error, your root folder name is CENTERGROUP_ROOT?

**Comment by FereshtehFeiz** [comment]
I did this in bash 
export PYTHONPATH="${center-group}:/path/to/project" 
and then add this in train.py
import sys
sys.path.append('$center-group')
