### ISSUE TITLE
RuntimeError: The size of tensor a (0) must match the size of tensor b (2) at non-singleton dimension 0

### ISSUE THREAD

**Issue by calmiLovesAI** [dvl-tum/center-group#7]
```
TRAINING FROM SCRATCH
NHEADS 4
NO WEIGHT SHARING!!!
/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp.py:21: LightningDeprecationWarning: The `pl.plugins.training_type.ddp.DDPPlugin` is deprecated in v1.6 and will be removed in v1.8. Use `pl.strategies.ddp.DDPStrategy` instead.
  "The `pl.plugins.training_type.ddp.DDPPlugin` is deprecated in v1.6 and will be removed in v1.8."
/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:293: LightningDeprecationWarning: Passing `Trainer(accelerator='ddp')` has been deprecated in v1.5 and will be removed in v1.7. Use `Trainer(strategy='ddp')` instead.
  f"Passing `Trainer(accelerator={accelerator!r})` has been deprecated"
/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:313: LightningDeprecationWarning: Passing <pytorch_lightning.plugins.training_type.ddp.DDPPlugin object at 0x7f91ff3999d0> `strategy` to the `plugins` flag in Trainer has been deprecated in v1.5 and will be removed in v1.7. Use `Trainer(strategy=<pytorch_lightning.plugins.training_type.ddp.DDPPlugin object at 0x7f91ff3999d0>)` instead.
  f"Passing {plugin} `strategy` to the `plugins` flag in Trainer has been deprecated"
Using 16bit native Automatic Mixed Precision (AMP)
/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/callback_connector.py:152: LightningDeprecationWarning: Setting `Trainer(checkpoint_callback=<pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint object at 0x7f91ff3958d0>)` is deprecated in v1.5 and will be removed in v1.7. Please consider using `Trainer(enable_checkpointing=<pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint object at 0x7f91ff3958d0>)`.
  f"Setting `Trainer(checkpoint_callback={checkpoint_callback})` is deprecated in v1.5 and will "
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name             | Type                  | Params
-----------------------------------------------------------
0 | bu_model         | AssociativeEmbedding_ | 28.6 M
1 | kp_embed_cnn     | Sequential            | 595 K 
2 | person_embed_cnn | Sequential            | 595 K 
3 | pos_embed        | PositionEmbeddingSine | 0     
4 | group_model      | GroupingModel         | 2.3 M 
-----------------------------------------------------------
32.2 M    Trainable params
0         Non-trainable params
32.2 M    Total params
64.330    Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]loading annotations into memory...
Done (t=0.47s)
creating index...
index created!
=> num_images: 8000
/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:245: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 6 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  category=PossibleUserWarning,
Sanity Checking DataLoader 0:   0%|                                                                                                            | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/train.py", line 129, in <module>
    main()
  File "tools/train.py", line 126, in main
    trainer.fit(model, datamodule, ckpt_path=ckpt_path)
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 769, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 719, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_train
    self._run_sanity_check()
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1411, in _run_sanity_check
    val_loop.run()
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 153, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 127, in advance
    output = self._evaluation_step(**kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 222, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1763, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/strategies/ddp.py", line 347, in validation_step
    return self.model(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/pytorch_lightning/overrides/base.py", line 93, in forward
    return self.module.validation_step(*inputs, **kwargs)
  File "/home/featurize/center/centergroup/models/centergroup.py", line 151, in validation_step
    return self.forward(**batch, return_loss=False)
  File "/home/featurize/center/centergroup/models/centergroup.py", line 140, in forward
    return self.forward_test(batch, multiscale=multiscale)
  File "/home/featurize/center/centergroup/models/centergroup.py", line 91, in forward_test
    preds, preds_flip = _split_flip_group_preds(preds, batch_idx = person_batch['batch'])        
  File "/home/featurize/center/centergroup/core/flip_utils.py", line 49, in _split_flip_group_preds
    assert (torch.unique(batch_idx) == torch.as_tensor([0, 1], device=batch_idx.device)).all(), "Predictions contain more than 1 image!"
RuntimeError: The size of tensor a (0) must match the size of tensor b (2) at non-singleton dimension 0
```

**Comment by calmiLovesAI** [comment]
I print the `batch_idx` while training:
```
batch_idx == tensor([], device='cuda:0', dtype=torch.int64)
```

**Comment by FereshtehFeiz** [comment]
Could you fix the problem of runtime error?

**Comment by calmiLovesAI** [comment]
> Could you fix the problem of runtime error?

Perhaps I cannot. I found the reason for this error seem to be input tensor's size, maybe the training code didn't read or process the input data correctly. That's all my own guess. The code is based on MMCV, MMPose and PyTorch Lightning, which means it's hard to debug.

**Comment by guillembraso** [comment]
Hi,

Sorry for my late reply, I've been sick. I'll have a look at this over the following days and get back to you!
